#define NORMAL_DLL						0			// 通用
#define	CJZQ_DLL						1			// 长江证券
#define	DYCY_DLL						2			// 第一创业
#define	DGZQ_DLL						3			// 东莞证券
#define	GXZQ_DLL						4			// 国信证券
#define	HTZQ_DLL						5			// 汉唐证券
#define	LHZQ_DLL						6			// 联合证券
#define	PAZQ_DLL						7			// 平安证券
#define	TQZQ_DLL						8			// 天勤证券
#define	MAZQ_DLL						9			// 民安证券
#define	JQZQ_DLL						10			// 健桥证券
#define	TTZQ_DLL						11			// 天同证券
#define	GFZQ_DLL						12			// 广发证券
#define DTZQ_DLL						13			// 大通证券
#define	HXZQ_DLL						14			// 华西证券
#define	XYZQ_DLL						15			// 兴业证券
#define	ZSZQ_DLL						16			// 招商证券
#define	JYZQ_DLL						17			// 金元证券
#define	ZXJT_DLL						18			// 中信建投
#define	YNHT_DLL						19			// 红塔证券
#define	CCZQ_DLL						20			// 长城证券
#define	HYZQ_DLL						21			// 宏源证券
#define	GTJA_DLL						22			// 国泰君安
#define	SJZQ_DLL						23			// 世纪证券
#define	AXZQ_DLL						24			// 安信证券
#define	CFZQ_DLL						25			// 财富证券
#define	DXZQ_DLL						26			// 东兴证券(闽发证券)
#define	YHZQ_DLL						27			// 银河证券
#define	GDZQ_DLL						28			// 光大证券
#define YDZQ_DLL						29			// 英大证券
#define DBZQ_DLL						30			// 德邦证券
#define	NJZQ_DLL						31			// 南京证券
#define ZXZQ_DLL						32			// 中信证券
#define SHZQ_DLL						33			// 上海证券
#define HBZQ_DLL						34			// 华宝证券
#define AJZQ_DLL						35			// 爱建证券
#define QLZQ_DLL						36			// 齐鲁证券
#define ZYGJ_DLL						37			// 中银国际
#define MZZQ_DLL						38			// 民族证券
#define XCZQ_DLL						39			// 湘财证券
#define GJZQ_DLL						40			// 国金证券
#define SCZQ_DLL						41			// 首创证券
#define GLZQ_DLL						42			// 国联证券
#define HLZQ_DLL						43			// 华林证券
#define HFZQ_DLL						44			// 华福证券
#define GYZQ_DLL						45			// 国元证券
#define GZZQ_DLL						46			// 广州证券
#define FZZQ_DLL						47			// 方正证券
#define BHZQ_DLL						48			// 渤海证券
#define XNZQ_DLL						49			// 西南证券
#define XSDZQ_DLL						50			// 新时代证券
#define ZTZQ_DLL						51			// 中投证券
#define HRZQ_DLL						52			// 华融证券
#define SYWG_DLL						53			// 申银万国
#define SHHX_DLL						54			// 华鑫证券
#define NJHT_DLL						55			// 华泰证券
#define JLDB_DLL						56			// 东北证券
#define MSZQ_DLL						57			// 民生证券
#define SXDT_DLL						58			// 大同证券
#define ZCZQ_DLL						59			// 众成证券
#define XMZQ_DLL						60			// 厦门证券
#define DFZQ_DLL						61			// 东方证券
#define YTZQ_DLL						62			// 银泰证券
#define ZXGJHK_DLL						63			// 中信国际HK
#define GDKGHK_DLL						64			// 光大控股HK
#define ZSXGHK_DLL						65			// 招商香港HK
#define BDZQHK_DLL						66			// 博大证券HK
#define JNZQ_DLL						67			// 江南证券
#define WHZQ_DLL						68			// 万和证券
#define HKZQ_DLL						69			// 航空证券
#define ZXWT_DLL						70			// 中信万通
#define XDZQ_DLL						71			// 信达证券
#define WKZQ_DLL						72			// 五矿证券
#define JHZQ_DLL						73			// 江海证券
#define HCZQ_DLL						74			// 华创证券
#define TPYZQ_DLL						75			// 太平洋证券
#define GHZQ_DLL						76			// 国海证券
#define DHZQ_DLL						77			// 东海证券
#define XBZQ_DLL						78			// 西部证券
#define SXZQ_DLL						79			// 山西证券
#define KYZQ_DLL						80			// 开源证券
#define HAZQ_DLL						81			// 华安证券
#define GXZQHK_DLL						82			// 国信证券HK
#define GSZQ_DLL						83			// 国盛证券
#define ZJZXJT_DLL						84			// 中信金通
#define SCHX_DLL						85			// 和兴证券
#define XHJHK_DLL						86			// 新鸿基HK
#define QFZQHK_DLL						87			// 侨丰证券HK
#define RFZQHK_DLL						88			// 日发证券HK
#define WLZQ_DLL						89			// 万联证券
#define LNZT_DLL						90			// 中天证券
#define XDGJHK_DLL						91			// 信达国际HK
#define NMHT_DLL						92			// 恒泰证券
#define TFZQ_DLL						93			// 天风证券
#define GSHL_DLL						94			// 华龙证券
#define RXZQ_DLL						95			// 日信证券
#define ZHZQ_DLL						96			// 中航证券
#define DFXGHK_DLL						97			// 东方香港HK
#define CTZQ_DLL						98			// 财通证券
#define YFJHK_DLL						99			// 永丰金HK
#define NFJJ_DLL						100			// 南方基金
#define YXZQHK_DLL						101			// 越秀证券HK
#define SHHT_DLL						102			// 海通证券
#define DWZQ_DLL						103			// 东吴证券

#define	MAX_QSID						103			// 最大券商ID


#define SZAG				0						// 深圳A股
#define SHAG				1						// 上海A股
#define SZBG				2						// 深圳B股
#define SHBG				3						// 上海B股
#define SZGZ				4						// 深圳国债
#define SHGZ				5						// 上海国债
#define SHHY				8						// 深沪合一(资金帐号)
#define KHWT				9						// 客户号委托
#define SBAG				12						// 三板A股
#define SBBG				13 						// 三板B股
#define SBGB				14						// 三板G股

#define CODE_NONE	-1						//市场不明
#define CODE_SZ		0						//深圳
#define CODE_SH		1						//上海
#define CODE_SZSH	2						//深圳、上海都可能
